export interface IDataRecord {
    eventId: number;
    animalId: string;
    cowId: number;
    healthIndex: string | '';
    endDate?: number;
    minValueDateTime?: number;
    cowEntryStatus?: string;
    newborns?: string;
    type: string;
    sire?: string;
    deletable: boolean;
    interval?: number;
    lactationNumber: number;
    oldLactationNumber?: number;
    daysInLactation: number;
    birthDateCalculated?: boolean;
    ageInDays: number;
    startDateTime: number;
    endDateTime?: number;
    reportingDateTime: number;
    alertType?: string;
    duration?: number;
    originalStartDateTime?: number;
    daysInPregnacy?: number;
    healthIndexPeack?: number;
    newGroupId?: number;
    newGroupName?: string;
    currentGroupName?: string;
    destinationGroup?: number;
    destinationGroupName?: string;
    breedingNumber?: number;
    isOutOfBreedingWindow?: boolean;
    calvingEase?: string;
}

// eventId: number;
// animalId: string;
// cowId: number;
// healthIndex?: number;
// endDate?: number;
// minValueDateTime?: number;
// cowEntryStatus?: string;
// newborns?: string;
// type: string;
// sire?: string;
// deletable: boolean;
// interval?: number;
// lactationNumber: number;
// oldLactationNumber?: number;
// daysInLactation: number;
// birthDateCalculated?: boolean;
// ageInDays: number;
// startDateTime: number;
// endDateTime?: number;
// reportingDateTime: number;
// alertType?: string;
// duration?: number;
// originalStartDateTime?: number;
// daysInPregnacy?: number;
// healthIndexPeack?: number;
// newGroupId?: number;
// newGroupName?: string;
// currentGroupName?: string;
// destinationGroup?: number;
// destinationGroupName?: string;
// breedingNumber?: number;
// isOutOfBreedingWindow?: boolean;
// calvingEase?: string;